version: '3.9'
name: seminar-keycloak

services:
  mysql-demo:
    image: mysql:8.0
    container_name: mysql-demo
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/keycloak:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak-demo:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak-demo
    command: [ "start-dev", "--import-realm" ]
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql-demo:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080

      KC_LOG_LEVEL: info
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

#      KC_SPI_THEME_DEFAULT: 'Custom Theme'
    ports:
      - 8181:8080
    depends_on:
      - mysql-demo
    volumes:
      - ./data/keycloak/import:/opt/keycloak/data/import
      - ./data/keycloak/themes:/opt/keycloak/themes
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network: